[tox]
envlist = py310
[testenv]
## I am forced to maintain two dependency lists because the following code
## to read from setup.py has failed
##deps = .[all_require]
deps =
  pytest
  requests==2.31.0
  pytz==2019.3
  python-dateutil==2.8.1
  PythonAPIClientBase==0.0.15
commands = python -m pytest
